<?php
/**
 * Defining fields for modular content
 *
 * @package Mtm_Field_Definitions
 * @author Marktime Media
 **/
class Mtm_Block_Field_Definitions {

	// Single Content Area
	public function mtm_block_single_content_area( $label = 'Single Content Block' ) {
		return apply_filters( 'mtm_block_single_content_area_filter', array(
			'key' => '56f57790d388fblock',
			'name' => 'mtm_module_single_content_area',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_570bd9354d780block',
					'label' => 'Content Area Title',
					'name' => 'mtm_text_area_title',
					'type' => 'text',
					'instructions' => 'Optional title for content area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f577e03cf7eblock',
					'label' => 'Content Area',
					'name' => 'mtm_module_text_area',
					'type' => 'wysiwyg',
					'instructions' => 'Add text, images, links, forms, or shortcodes',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-single-content-area',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
		));
	}


	// Dual Content Area
	public static function mtm_block_dual_content_area( $label = 'Dual Content Block' ) {
		return apply_filters( 'mtm_block_dual_content_area_filter', array(
			'key' => '56f579364c61eblock',
			'name' => 'mtm_module_dual_content_area',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_570bd9de4d781block',
					'label' => 'Content Area Title',
					'name' => 'mtm_text_area_title',
					'type' => 'text',
					'instructions' => 'Optional title for content area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f579564c61fblock',
					'label' => 'Content Area',
					'name' => 'mtm_module_text_area',
					'type' => 'wysiwyg',
					'instructions' => 'Add text, images, links, forms, or shortcodes',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array(
					'key' => 'field_56f5797e4c620block',
					'label' => 'Content Area',
					'name' => 'mtm_module_text_area_2',
					'type' => 'wysiwyg',
					'instructions' => 'Add text, images, links, forms, or shortcodes',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-dual-content-area',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Content + Callout
	public static function mtm_block_content_callout( $label = 'Content + Callout Block' ) {
		return apply_filters( 'mtm_block_content_callout_filter', array(
			'key' => '57a203ad1549dblock',
			'name' => 'mtm_module_content_callout',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_57a203ad1549eblock',
					'label' => 'Content Area Title',
					'name' => 'mtm_text_area_title',
					'type' => 'text',
					'instructions' => 'Optional title for content area (leave blank for no title)',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_57a203ad1549fblock',
					'label' => 'Content Area',
					'name' => 'mtm_module_text_area',
					'type' => 'wysiwyg',
					'instructions' => 'Add text, images, links, forms, or shortcodes',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => '',
				),
				array(
					'key' => 'field_57a203ad154a0block',
					'label' => 'Callout Area',
					'name' => 'mtm_module_text_area_2',
					'type' => 'wysiwyg',
					'instructions' => 'This content will appear in the callout area and may have custom styles',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => '',
				),
				array(
					'key' => 'field_5a00b31338751block',
					'label' => 'Callout Background Image',
					'name' => 'mtm_callout_background_image',
					'type' => 'image',
					'instructions' => 'Add an optional background image for the callout area. Any text added to the callout area will appear on top of the image.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-content-callout',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Hero Image
	public static function mtm_block_hero_image( $label = 'Hero Image' ) {
		return apply_filters( 'mtm_block_hero_image_filter', array(
			'key' => '56f57f3e501f2block',
			'name' => 'mtm_module_hero_image',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_56fe9f30fa59eblock',
					'label' => 'Select Title',
					'name' => 'mtm_hero_select_title',
					'type' => 'radio',
					'instructions' => 'Which title should we show with this content?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Page Title' => 'Page Title',
						'Custom Headline' => 'Custom Headline',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_56f57f57501f3block',
					'label' => 'Headline',
					'name' => 'mtm_hero_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56fe9f30fa59eblock',
								'operator' => '==',
								'value' => 'Custom Headline',
							),
						),
					),
					'wrapper' => array (
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f580cace231block',
					'label' => 'Image',
					'name' => 'mtm_hero_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_56f57f6e501f4block',
					'label' => 'Subheading/Content',
					'name' => 'mtm_hero_subheading',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 60,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array(
					'key' => 'field_56f57fcd501f6block',
					'label' => 'Add Buttons',
					'name' => 'mtm_home_button_repeater',
					'type' => 'repeater',
					'instructions' => '(Optional) Click "Add Buttion" to add call to action buttons',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Button',
					'sub_fields' => array(
						array(
							'key' => 'field_56f57fe4501f7block',
							'label' => 'Button Label',
							'name' => 'mtm_home_button_label',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_57730a1ac9370block',
							'label' => 'Button Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link your button to other content on your site',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_56f57ffb501f8block',
							'label' => 'Button Custom Link',
							'name' => 'mtm_home_button_link',
							'type' => 'text',
							'instructions' => 'Link your button to a custom url or anchor tag (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-hero-image',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Video/Media
	public static function mtm_block_hero_media( $label = 'Video/Media' ) {
		return apply_filters( 'mtm_block_hero_media_filter', array(
			'key' => '57813bcb6a7a1ë',
			'name' => 'mtm_module_hero_media',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_57813bcb6a7a2block',
					'label' => 'Image, Video, or Other Content?',
					'name' => 'mtm_hero_select_media',
					'type' => 'radio',
					'instructions' => 'Add video, or other embedded content. See https://codex.wordpress.org/Embeds for what is allowed.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Video' => 'Video',
						'Other Media' => 'Other Media',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_57813bcb6a7a3block',
					'label' => 'Select Title',
					'name' => 'mtm_hero_select_title',
					'type' => 'radio',
					'instructions' => 'Which title should we show with this content?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Page Title' => 'Page Title',
						'Custom Headline' => 'Custom Headline',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_57813bcb6a7a4block',
					'label' => 'Headline',
					'name' => 'mtm_hero_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_57813bcb6a7a3block',
								'operator' => '==',
								'value' => 'Custom Headline',
							),
						),
					),
					'wrapper' => array(
						'width' => 35,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_57813bcb6a7a6block',
					'label' => 'Embedded Media',
					'name' => 'mtm_hero_embed',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_57813bcb6a7a2block',
								'operator' => '==',
								'value' => 'Video',
							),
						),
						array(
							array(
								'field' => 'field_57813bcb6a7a2block',
								'operator' => '==',
								'value' => 'Other',
							),
						),
					),
					'wrapper' => array(
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'width' => '',
					'height' => '',
				),
				array(
					'key' => 'field_57813bcb6a7a7block',
					'label' => 'Subheading/Content',
					'name' => 'mtm_hero_subheading',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => 60,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => '',
				),
				array(
					'key' => 'field_57813bcb6a7a8block',
					'label' => 'Add Buttons',
					'name' => 'mtm_home_button_repeater',
					'type' => 'repeater',
					'instructions' => '(Optional) Click "Add Buttion" to add call to action buttons',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Button',
					'sub_fields' => array(
						array(
							'key' => 'field_57813bcb6a7a9block',
							'label' => 'Button Label',
							'name' => 'mtm_home_button_label',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_57813bcb6a7aablock',
							'label' => 'Button Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link your button to other content on your site',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_57813bcb6a7abblock',
							'label' => 'Button Custom Link',
							'name' => 'mtm_home_button_link',
							'type' => 'text',
							'instructions' => 'Link your button to a custom url or anchor tag (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-hero-media',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Slider
	public static function mtm_block_slider( $label = 'Slider' ) {
		return apply_filters( 'mtm_block_slider_filter', array(
			'key' => '57815762d2d5eblock',
			'name' => 'mtm_module_slider',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_57815771d2d5fblock',
					'label' => 'Add Slides',
					'name' => 'mtm_slider_add_slides',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_578159add2d60block',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Slide',
					'sub_fields' => array(
						array(
							'key' => 'field_578159add2d60block',
							'label' => 'Headline',
							'name' => 'mtm_hero_headline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_57815a19d2d61block',
							'label' => 'Subheading/Content',
							'name' => 'mtm_hero_subheading',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array(
							'key' => 'field_57815a24d2d62block',
							'label' => 'Image',
							'name' => 'mtm_hero_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_57815a30d2d63block',
							'label' => 'Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link your button to other content on your site',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_57815a65d2d64block',
							'label' => 'Custom Link',
							'name' => 'mtm_home_button_link',
							'type' => 'text',
							'instructions' => 'Link your button to a custom url or anchor tag (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-slider',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Feature Boxes
	public static function mtm_block_feature_boxes( $label = 'Feature Boxes' ) {
		return apply_filters( 'mtm_block_feature_boxes_filter', array(
			'key' => '56f579d6aaafbblock',
			'name' => 'mtm_module_feature_boxes',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_570bd9354d799block',
					'label' => 'Feature Box Title',
					'name' => 'mtm_text_area_title',
					'type' => 'text',
					'instructions' => 'Optional title for feature boxes (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f579f9aaafcblock',
					'label' => 'Add Featured Content Boxes',
					'name' => 'mtm_home_featured_content_boxes',
					'type' => 'repeater',
					'instructions' => 'Click "Add Feature Box" to create a new box, then choose whether to display specific site content, the latest post from a term, or manual input',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_56f57a25aaafdblock',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Feature Box',
					'sub_fields' => array(
						array(
							'key' => 'field_56f57a25aaafdblock',
							'label' => 'Which Type Of Featured Content?',
							'name' => 'mtm_home_featured_type',
							'type' => 'radio',
							'instructions' => 'Select how you want to get content for this feature box',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Specific Content' => 'Specific Content',
								'Show Latest Post' => 'Show Latest Post',
								'Manual Entry' => 'Manual Entry',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
						),
						array(
							'key' => 'field_56f57a7baaafeblock',
							'label' => 'Content Box Title',
							'name' => 'mtm_home_featured_box_title',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Show Latest Post',
									),
								),
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Specific Content',
									),
								),
							),
							'wrapper' => array(
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Post Title' => 'Post Title',
							),
							'allow_null' => 0,
							'other_choice' => 1,
							'save_other_choice' => 0,
							'default_value' => 'Add Custom Title Here',
							'layout' => 'vertical',
						),
						array(
							'key' => 'field_56f57ab7aab00block',
							'label' => 'Content Box Title',
							'name' => 'mtm_home_featured_box_manual_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Manual Entry',
									),
								),
							),
							'wrapper' => array(
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_56f57aceaab01block',
							'label' => 'Specific Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Specific Content',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_56f57aeeaab02block',
							'label' => 'Select Specific Content',
							'name' => 'mtm_home_featured_select_single',
							'type' => 'post_object',
							'instructions' => 'Select specific content to use as the source for your feature box',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
						array(
							'key' => 'field_56f57b0aaab03block',
							'label' => 'Show Latest Post',
							'name' => 'show_latest_post',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Show Latest Post',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_56f57b1faab04block',
							'label' => 'Select Post Taxonomy Term',
							'name' => 'mtm_home_featured_archive_taxonomy',
							'type' => 'taxonomy-chooser',
							'instructions' => 'Use the latest post from a specific term as the content for this feature box',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Show Latest Post',
									),
								),
							),
							'wrapper' => array(
								'width' => 70,
								'class' => '',
								'id' => '',
							),
							'tax_type' => 0,
							'choices' => '',
							'type_value' => 1,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_5783e5lmnop03495block',
							'label' => 'Random Post?',
							'name' => 'mtm_randomize',
							'type' => 'true_false',
							'instructions' => 'Will show random rather than latest post',
							'required' => '',
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Show Latest Post',
									),
								),
							),
							'wrapper' => array(
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
						array(
							'key' => 'field_56f57e5eaab05block',
							'label' => 'Manual Content Entry',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Manual Entry',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_56f57e76aab06block',
							'label' => 'Featured Image',
							'name' => 'mtm_home_featured_image_manual',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Manual Entry',
									),
								),
							),
							'wrapper' => array(
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_56f57ea0aab07block',
							'label' => 'Featured Content',
							'name' => 'mtm_home_featured_content_manual',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Manual Entry',
									),
								),
							),
							'wrapper' => array(
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
						),
						array(
							'key' => 'field_56f57ee7aab09block',
							'label' => 'Content Link',
							'name' => 'mtm_home_featured_content_link_manual',
							'type' => 'page_link',
							'instructions' => 'Link to a custom page or post on your site',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_56f57a25aaafdblock',
										'operator' => '==',
										'value' => 'Manual Entry',
									),
								),
							),
							'wrapper' => array(
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_56f57f03aab0ablock',
							'label' => 'Custom Link',
							'name' => 'mtm_home_featured_content_link_custom',
							'type' => 'text',
							'instructions' => 'If you don\'t wish to link to a page or post on your site, type your custom link here. Overrides content link.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 60,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-feature-boxes',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Call To Action
	public static function mtm_block_call_to_action( $label = 'Call To Action' ) {
		return apply_filters( 'mtm_block_call_to_action_filter', array(
			'key' => '56f58e7c5bc87block',
			'name' => 'mtm_module_call_to_action',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_56f58fe05bc88block',
					'label' => 'Call To Action Headline',
					'name' => 'mtm_cta_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f590105bc89block',
					'label' => 'Subheading/Content',
					'name' => 'mtm_cta_subheading',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
				),
				array(
					'key' => 'field_56f5902f5bc8ablock',
					'label' => 'CTA Buttons',
					'name' => 'mtm_cta_button_repeater',
					'type' => 'repeater',
					'instructions' => 'Click "Add Button" to add call to action buttons that will lead to other pages, other sections within a page, or elsewhere.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Button',
					'sub_fields' => array(
						array(
							'key' => 'field_56f5904a5bc8bblock',
							'label' => 'CTA Button Label',
							'name' => 'mtm_cta_button_label',
							'type' => 'text',
							'instructions' => 'The text that will show up on your call to action button',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_57730910c936fblock',
							'label' => 'CTA Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link your button to other content on your site',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_56f590765bc8cblock',
							'label' => 'CTA Button Link',
							'name' => 'mtm_cta_button_link',
							'type' => 'text',
							'instructions' => 'Link your button to an anchor tag on the same page, or a custom url (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-call-to-action',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Logo/Graphic Showcase
	public static function mtm_block_logo_showcase( $label = 'Logo/Graphic Showcase' ) {
		return apply_filters( 'mtm_block_logo_showcase_filter', array(
			'key' => '56f59482418efblock',
			'name' => 'mtm_module_logo_showcase',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_56feb088a4a16block',
					'label' => 'Logo/Graphic Area Title',
					'name' => 'mtm_logo_title',
					'type' => 'text',
					'instructions' => 'Optional title for the logo/graphic area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_56f59494418f0block',
					'label' => 'Add Logo/Graphic',
					'name' => 'mtm_logo_repeater',
					'type' => 'repeater',
					'instructions' => 'Click "Add Logo" to add a logo/graphic showcase to your page (transparent PNG images preferred for logos)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_56f594e1418f1block',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Logo',
					'sub_fields' => array(
						array(
							'key' => 'field_56f594e1418f1block',
							'label' => 'Logo/Graphic',
							'name' => 'mtm_logo_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5773089ac936eblock',
							'label' => 'Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link to specific content on your site',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array(
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_56f594fd418f2block',
							'label' => 'Custom Link',
							'name' => 'mtm_logo_link',
							'type' => 'text',
							'instructions' => 'Link to a custom url (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-logo-showcase',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Widget Area
	public static function mtm_block_widget_area( $label = 'Widget Area' ) {
		return apply_filters( 'mtm_block_widget_area_filter', array(
			'key' => '570bd7f0a52c7block',
			'name' => 'mtm_module_widget_area',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_570bd7fba52c8block',
					'label' => 'Widget Area Title',
					'name' => 'mtm_widget_area_title',
					'type' => 'text',
					'instructions' => 'Optional title for widget area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_570bd811a52c9block',
					'label' => 'Select Widget Area',
					'name' => 'mtm_select_widget_area',
					'type' => 'widget_area',
					'instructions' => 'Select which widget area to show. You can add widgets to this area under Appearance > Widgets.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_null' => 1,
					'display_or_return' => 'return',
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-widget-area',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Manual List
	public static function mtm_block_list_manual( $label = 'Manual List' ) {
		return apply_filters( 'mtm_block_list_manual_filter', array(
			'key' => '5728d653cf63fblock',
			'name' => 'mtm_module_listgrid',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_5728dc4b35580block',
					'label' => 'List Title',
					'name' => 'mtm_list_title',
					'type' => 'text',
					'instructions' => 'Optional title for list area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5728d666cf640block',
					'label' => 'Add List Item',
					'name' => 'mtm_add_list_item',
					'type' => 'repeater',
					'instructions' => 'Click "Add List Item" to create a new list row',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5728d690cf641block',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add List Item',
					'sub_fields' => array(
						array(
							'key' => 'field_5728d690cf641block',
							'label' => 'Heading',
							'name' => 'mtm_list_item_heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_5772ff2b7839eblock',
							'label' => 'Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link to specific content on your site',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_5728eaf86b3cablock',
							'label' => 'Custom Link',
							'name' => 'mtm_list_item_link',
							'type' => 'url',
							'instructions' => 'Link to a custom url (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5728d6b0cf642block',
							'label' => 'Content',
							'name' => 'mtm_list_item_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
						),
						array(
							'key' => 'field_57730099184bdblock',
							'label' => 'File (optional)',
							'name' => 'mtm_list_item_file',
							'type' => 'file',
							'instructions' => 'Include a file with this list item',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5728d6c7cf643block',
							'label' => 'Image (optional)',
							'name' => 'mtm_list_item_image',
							'type' => 'image',
							'instructions' => 'Include an image with this list item',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-list-manual',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Manual Grid
	public static function mtm_block_grid_manual( $label = 'Manual Grid' ) {
		return apply_filters( 'mtm_block_grid_manual_filter', array(
			'key' => '576a88e224ba2block',
			'name' => 'mtm_module_gridlist',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_576a88e224ba3block',
					'label' => 'Grid Title',
					'name' => 'mtm_list_title',
					'type' => 'text',
					'instructions' => 'Optional title for grid area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_576bec54e5801block',
					'label' => 'Number of Items Per Row?',
					'name' => 'mtm_grid_archive_per_row',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => 3,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => 6,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_576a88e224ba8block',
					'label' => 'Add Grid Item',
					'name' => 'mtm_add_list_item',
					'type' => 'repeater',
					'instructions' => 'Click "Add Grid Item" to create a new Grid block',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_576a88e224ba9block',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Grid Item',
					'sub_fields' => array(
						array(
							'key' => 'field_576a88e224ba9block',
							'label' => 'Heading',
							'name' => 'mtm_list_item_heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_5773000c184bbblock',
							'label' => 'Content Link',
							'name' => 'mtm_post_content_link',
							'type' => 'page_link',
							'instructions' => 'Link to specific content on your site',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array(
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_576a88e224baablock',
							'label' => 'Custom Link',
							'name' => 'mtm_list_item_link',
							'type' => 'url',
							'instructions' => 'Link to a custom url (overrides Content Link)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_576a88e224babblock',
							'label' => 'Content',
							'name' => 'mtm_list_item_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
						),
						array(
							'key' => 'field_57730067184bcblock',
							'label' => 'File (optional)',
							'name' => 'mtm_list_item_file',
							'type' => 'file',
							'instructions' => 'Include a file with this grid item',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_576a88e224bacblock',
							'label' => 'Image (optional)',
							'name' => 'mtm_list_item_image',
							'type' => 'image',
							'instructions' => 'Include an image with this grid item',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-grid-manual',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Post List
	public static function mtm_block_list_posts( $label = 'Post List' ) {
		return apply_filters( 'mtm_block_list_posts_filter', array(
			'key' => '5783de4c38883block',
			'name' => 'mtm_module_listgrid_posts',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_5783de4c38884block',
					'label' => 'List Title',
					'name' => 'mtm_list_title',
					'type' => 'text',
					'instructions' => 'Optional title for list area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5783de4c38885block',
					'label' => 'Content Source',
					'name' => 'mtm_list_archive_select',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Add Posts Manually' => 'Add Posts Manually',
						'Pick From Taxonomy' => 'Pick From Taxonomy',
						'Pick From Post Type' => 'Pick From Post Type',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_5783de4c38886block',
					'label' => 'Select Source',
					'name' => 'mtm_list_archive_taxonomy',
					'type' => 'taxonomy-chooser',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885block',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
					),
					'wrapper' => array(
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'tax_type' => 0,
					'choices' => '',
					'type_value' => 1,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5783de4c38887block',
					'label' => 'Select Post Type',
					'name' => 'mtm_list_archive_post_type',
					'type' => 'post_type_selector',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885block',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'select_type' => 0,
				),
				array(
					'key' => 'field_5783e5dabcde03495block',
					'label' => 'Randomize Posts?',
					'name' => 'mtm_randomize',
					'type' => 'true_false',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885block',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
						array(
							array(
								'field' => 'field_5783de4c38885block',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
					),
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array(
					'key' => 'field_5783e66e808c7block',
					'label' => 'Select Content',
					'name' => 'mtm_list_archive_manual_posts',
					'type' => 'relationship',
					'instructions' => 'Add and reorder content to build your list. Use the search and filters to narrow down your selection.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885block',
								'operator' => '==',
								'value' => 'Add Posts Manually',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
					),
					'taxonomy' => array(
					),
					'filters' => array(
						0 => 'search',
						1 => 'post_type',
						2 => 'taxonomy',
					),
					'elements' => array (
						0 => 'featured_image',
					),
					'min' => '',
					'max' => '',
					'return_format' => 'object',
				),
				array(
					'key' => 'field_5783de4c38888block',
					'label' => 'Total Number of Items?',
					'name' => 'mtm_list_archive_taxonomy_number',
					'type' => 'number',
					'instructions' => 'How many total items do you want to display in this list?',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885block',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
						array(
							array(
								'field' => 'field_5783de4c38885block',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => 3,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5783e5d7808c5block',
					'label' => 'Show Taxonomy Links?',
					'name' => 'mtm_show_taxonomy_links',
					'type' => 'true_false',
					'instructions' => 'Do you want to show a list of terms to use as links/filters?',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array(
					'key' => 'field_5783e637808c6block',
					'label' => 'Which Taxonomy?',
					'name' => 'mtm_list_archive_taxonomy_links',
					'type' => 'taxonomy-chooser',
					'instructions' => 'Which taxonomy should we select to display the terms?',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783e5d7808c5block',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'tax_type' => 1,
					'choices' => '',
					'type_value' => 1,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_578f8e190874fblock',
					'label' => 'Show "View All" Link?',
					'name' => 'mtm_show_view_all_link',
					'type' => 'true_false',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de4c38885block',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
						array(
							array(
								'field' => 'field_5783de4c38885block',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Yes, add a "View All" link to the bottom of this list',
					'default_value' => 0,
				),
				array(
					'key' => 'field_57835e9283ur9834bbblock',
					'label' => 'View All Link Text',
					'name' => 'mtm_view_all_link_text',
					'type' => 'text',
					'instructions' => 'Optional text for Veiw All link',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_578f8e190874fblock',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-list-posts',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Post Grid
	public static function mtm_block_grid_posts( $label = 'Post Grid' ) {
		return apply_filters( 'mtm_block_grid_posts_filter', array(
			'key' => '5783de5e38890block',
			'name' => 'mtm_module_gridlist_posts',
			'label' => $label,
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_5783de5e38891block',
					'label' => 'Grid Title',
					'name' => 'mtm_list_title',
					'type' => 'text',
					'instructions' => 'Optional title for grid area (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5783de5e38896block',
					'label' => 'Number of Items Per Row?',
					'name' => 'mtm_grid_archive_per_row',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => 3,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => 6,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5783de5e38892block',
					'label' => 'Content Source',
					'name' => 'mtm_list_archive_select',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Add Posts Manually' => 'Add Posts Manually',
						'Pick From Taxonomy' => 'Pick From Taxonomy',
						'Pick From Post Type' => 'Pick From Post Type',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'field_5783de5e38893block',
					'label' => 'Select Source',
					'name' => 'mtm_list_archive_taxonomy',
					'type' => 'taxonomy-chooser',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
					),
					'wrapper' => array(
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'tax_type' => 0,
					'choices' => '',
					'type_value' => 1,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_5783de5e38894block',
					'label' => 'Select Post Type',
					'name' => 'mtm_list_archive_post_type',
					'type' => 'post_type_selector',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'select_type' => 0,
				),
				array(
					'key' => 'field_5783e5dzyxwv03495block',
					'label' => 'Randomize Posts?',
					'name' => 'mtm_randomize',
					'type' => 'true_false',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892block',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
						array(
							array(
								'field' => 'field_5783de5e38892block',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array(
					'key' => 'field_5783dee83889eblock',
					'label' => 'Select Content',
					'name' => 'mtm_list_archive_manual_posts',
					'type' => 'relationship',
					'instructions' => 'Add and reorder content to build your grid. Use the search and filters to narrow down your selection.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892block',
								'operator' => '==',
								'value' => 'Add Posts Manually',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
					),
					'taxonomy' => array(
					),
					'filters' => array(
						0 => 'search',
						1 => 'post_type',
						2 => 'taxonomy',
					),
					'elements' => array (
						0 => 'featured_image',
					),
					'min' => '',
					'max' => '',
					'return_format' => 'object',
				),
				array(
					'key' => 'field_5783de5e38895block',
					'label' => 'Total Number of Items?',
					'name' => 'mtm_list_archive_taxonomy_number',
					'type' => 'number',
					'instructions' => 'How many total items do you want to display in this grid?',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892block',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
						array(
							array(
								'field' => 'field_5783de5e38892block',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => 3,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5783dfaa3889fblock',
					'label' => 'Show Taxonomy Links?',
					'name' => 'mtm_show_taxonomy_links',
					'type' => 'true_false',
					'instructions' => 'Do you want to show a list of terms to use as links/filters?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array(
					'key' => 'field_5783e0e0388a0block',
					'label' => 'Which Taxonomy?',
					'name' => 'mtm_list_archive_taxonomy_links',
					'type' => 'taxonomy-chooser',
					'instructions' => 'Which taxonomy should we select to display the terms?',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783dfaa3889fblock',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'tax_type' => 1,
					'choices' => '',
					'type_value' => 1,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_578f8e4208750block',
					'label' => 'Show "View All" link?',
					'name' => 'mtm_show_view_all_link',
					'type' => 'true_false',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5783de5e38892block',
								'operator' => '==',
								'value' => 'Pick From Taxonomy',
							),
						),
						array(
							array(
								'field' => 'field_5783de5e38892block',
								'operator' => '==',
								'value' => 'Pick From Post Type',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Yes, add a "View All" link to the bottom of this grid',
					'default_value' => 0,
				),
				array(
					'key' => 'field_57835e9283ur9834block',
					'label' => 'View All Link Text',
					'name' => 'mtm_view_all_link_text',
					'type' => 'text',
					'instructions' => 'Optional text for Veiw All link',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_578f8e4208750block',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-grid-posts',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	// Tabs
	public function mtm_block_tabs( $label = 'Tabs' ) {
		return apply_filters( 'mtm_block_tabs_filter', array(
			'key' => '5a00b5acf261ablock',
			'name' => 'mtm_module_tabs',
			'label' => 'Tabs',
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_5a00b5bdf261bblock',
					'label' => 'Add Tabs',
					'name' => 'mtm_tab_repeater',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5a00b5ddf261cblock',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add New Tab',
					'sub_fields' => array(
						array(
							'key' => 'field_5a00b5ddf261cblock',
							'label' => 'Tab Title',
							'name' => 'mtm_tab_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5a00b5e8f261dblock',
							'label' => 'Tab Content',
							'name' => 'mtm_tab_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-tabs',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

	public function mtm_block_gallery( $label = 'Gallery Grid Block' ) {
		return apply_filters( 'mtm_block_gallery_filter', array(
			'key' => '5ae78714d3fadblock',
			'name' => 'mtm_module_gallery',
			'label' => 'Gallery',
			'display' => 'block',
			'fields' => array(
				array(
					'key' => 'field_5783de5e9843784ffblock',
					'label' => 'Gallery Title',
					'name' => 'mtm_list_title',
					'type' => 'text',
					'instructions' => 'Optional title for gallery (leave blank for no title)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5ae7871ca2605block',
					'label' => 'Gallery Images',
					'name' => 'mtm_module_gallery_images',
					'type' => 'gallery',
					'instructions' => 'Add images to output a WordPress gallery',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'min' => '',
					'max' => '',
					'insert' => 'append',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),

			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mtm-block-gallery',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => ''
		));
	}

} // END class
